import logging
import json
from urllib.error import URLError
from urllib.request import Request, urlopen

from state.workflow_state import WorkflowState


class CodeGenerationAgent:
    """Generate implementation guidance from planned tasks using Ollama."""

    def __init__(
        self,
        name: str = "Code Generation Agent",
        ollama_base_url: str = "http://localhost:11434",
        model: str = "llama3",
        fallback_to_template: bool = True,
    ) -> None:
        self.name = name
        self.ollama_base_url = ollama_base_url.rstrip("/")
        self.model = model
        self.fallback_to_template = fallback_to_template

    def _build_prompt(self, state: WorkflowState) -> str:
        lines = [
            "You are a senior software engineer.",
            "Generate a concise implementation plan in Markdown.",
            "For each task include: architecture notes, implementation steps, and test strategy.",
            "Requirement:",
            state["user_input"],
            "",
            "Planned tasks:",
        ]

        for task in state["planned_tasks"]:
            lines.append(f"- Task {task['id']}: {task['title']} ({task['description']})")

        return "\n".join(lines)

    def _generate_with_ollama(self, prompt: str) -> str:
        payload = json.dumps(
            {
                "model": self.model,
                "prompt": prompt,
                "stream": False,
            }
        ).encode("utf-8")

        request = Request(
            url=f"{self.ollama_base_url}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        with urlopen(request, timeout=60) as response:
            body = response.read().decode("utf-8")
            result = json.loads(body)
            output = result.get("response", "").strip()

            if not output:
                raise ValueError("Ollama returned an empty response")

            return output

    def _template_fallback(self, state: WorkflowState) -> str:
        output_lines = [
            "# Generated Implementation Plan",
            "",
            "The following implementation plan was generated by the fallback template path:",
            "",
        ]

        for task in state["planned_tasks"]:
            output_lines.append(f"## Task {task['id']}: {task['title']}")
            output_lines.append(f"- Description: {task['description']}")
            output_lines.append("- Suggested Action: Implement and test this task.")
            output_lines.append("")

        return "\n".join(output_lines)

    def run(self, state: WorkflowState) -> WorkflowState:
        logging.info("[%s] Started output generation", self.name)

        if not state["planned_tasks"]:
            state["status"] = "failed"
            state["errors"].append("No planned tasks found")
            return state

        prompt = self._build_prompt(state)

        try:
            generated_output = self._generate_with_ollama(prompt)
            state["generation_source"] = "ollama"
        except (URLError, OSError, TimeoutError, ValueError, json.JSONDecodeError) as error:
            logging.error("[%s] Ollama generation failed: %s", self.name, error)
            state["errors"].append(f"Ollama generation failed: {error}")

            if not self.fallback_to_template:
                state["generation_source"] = "ollama_failed"
                state["status"] = "failed"
                return state

            generated_output = self._template_fallback(state)
            state["generation_source"] = "template_fallback"

        state["generated_output"] = generated_output
        state["status"] = "generated"

        logging.info("[%s] Output generation completed", self.name)

        return state
