import logging

from state.workflow_state import WorkflowState
from tools.validation_tool import validation_tool


class ValidationAgent:
    """Validate the output generated by previous agents."""

    def __init__(self, name: str = "Validation Agent") -> None:
        self.name = name

    def run(self, state: WorkflowState) -> WorkflowState:
        logging.info("[%s] Started validation", self.name)

        output = state.get("generated_output")

        if output is None:
            state["status"] = "failed"
            state["errors"].append("No generated output found")
            return state

        result = validation_tool(output, expected_task_count=len(state["planned_tasks"]))

        state["validation_result"] = result
        state["status"] = "completed" if result["valid"] else "validation_failed"

        logging.info("[%s] Validation result: %s", self.name, result)

        return state
